### ISSUE TITLE
Switch to shuttle-control-usb NPM module?

### ISSUE THREAD

**Issue by peternewman** [legacymachine/node-red-contrib-shuttlexpress#2]
Hi,

You might like to switch to https://www.npmjs.com/package/shuttle-control-usb which has only recently been published to NPM, but seems to have existed for a while, which means this module could then handle the Shuttle Pro v1 and v2 as well!

**Comment by peternewman** [comment]
Thanks @dudleyjosh .

Would you be interested in adding support for non express devices, I've got one I can test with if you do, and make any required changes.

**Comment by dudleyjosh** [comment]
It looks like it should be easy to add them... I'll try to push an update
tomorrow and you can let me know if it works for you.

Thanks,
Josh

--------------------

"Don't let success go to your head. Don't let failure go to your heart."

**Comment by dudleyjosh** [comment]
I had some time tonight so I just pushed v1.0.1 which should support
ShuttlePro v1 & ShuttlePro v2 also.

Let me know if it works for you.

Josh

--------------------

"Don't let success go to your head. Don't let failure go to your heart."
