### ISSUE TITLE
Needs a `node.on('close', function(){ ... }` handler

### ISSUE THREAD

**Issue by hardillb** [legacymachine/node-red-contrib-shuttlexpress#3]
The node needs an on close handler (https://nodered.org/docs/creating-nodes/node-js#closing-the-node) to shutdown the USB Hid connection when the node is closed.

Something similar to the one used in the powermate node

https://github.com/hardillb/node-red-contrib-powermate/blob/019e5329be13c71d5e560b156598e0b088f076c7/powermate/powermate.js#L55

https://github.com/hardillb/node-powermate/blob/33f908cf970defc8f7b0802d9bac46763ec9996d/powermate.js#L211

This will allow Node-RED to exit gracefully when requested.

**Comment by dudleyjosh** [comment]
A close handler was added as suggested and the node now closes properly.
